version: "3"
services:

  dians-db:

    image: "postgres"

    container_name: "dias_container"

    environment:
      - POSTGRES_USER=dias
      - POSTGRES_PASSWORD=dias123
      - POSTGRES_DB=avto-servis

    ports:
      - "5436:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
